## Fallback copy for every level's brief, keyed by scene file name.
##
## LevelDescription reads its scene fields first and fills any that are empty
## from here. The scene fields are exported properties on a non-@tool script,
## and the editor has twice saved scenes without such values (the tutorial
## steps lost theirs the same way), which in the export showed up as block
## pictures with no text under them. Keep this in step with the scenes.
class_name LevelBriefs
extends RefCounted

const BRIEFS := {
	"tutorial_1": {
		"title": "First steps",
		"mission": "Get the robot onto the red flag.",
		"blocks": ["res://level/objects/entities/robot/blocks/move.tres"],
		"block_notes": ["Moves the robot one tile forward."],
	},
	"it_0a": {
		"title": "Read it first",
		"mission": "Watch this program run in both rooms. Why does the robot stop in a different place?",
		"twist": "Same program, two rooms. Only what's ahead of the robot is different.",
		"tip": "It runs by itself when the level opens. Press Play to watch it again.",
		"rooms": ["Finish on the flag.", "Stop right before the puddle."],
		"blocks": ["res://level/objects/entities/robot/blocks/ahead_is.tres", "res://puzzle/blocks/socket/not.tres", "res://puzzle/blocks/control flow/if.tres"],
		"block_notes": ["Checks the tile in front of the robot. Gives True or False.", "Flips True and False.", "Runs the blocks inside it only when its condition is True."],
		"block_values": ["puddle", "", ""],
		"show_stars": false,
	},
	"it_0b": {
		"title": "Rebuild it",
		"mission": "Build last level's program yourself. It runs in Room 1, then again in Room 2.",
		"twist": "But the canvas starts empty this time.",
		"rooms": ["Finish on the flag.", "Stop right before the puddle, not in it."],
	},
	"it_1": {
		"title": "Until the wall",
		"mission": "One program runs in all three rooms. Get the robot onto the flag in each one.",
		"twist": "Every hallway is a different length.",
		"rooms": ["A short hallway.", "A longer hallway.", "The longest hallway."],
		"blocks": ["res://puzzle/blocks/control flow/while.tres", "res://level/objects/entities/robot/blocks/ahead_is.tres", "res://puzzle/blocks/socket/not.tres"],
		"block_notes": ["Repeats the blocks inside it while its condition is True.", "Checks the tile in front: a wall, the flag, or a puddle.", "Flips True and False."],
	},
	"it_2": {
		"title": "Until you see it",
		"mission": "One program, three rooms. Finish on the flag in every room.",
		"twist": "The flag isn't at the end of the hall anymore.",
		"rooms": ["The flag is partway down the hall.", "The flag is further along.", "The flag is somewhere else again."],
		"blocks": ["res://level/objects/entities/robot/blocks/ahead_is.tres"],
		"block_notes": ["It can look for the flag too: pick destination."],
		"block_values": ["destination"],
	},
	"it_3": {
		"title": "Around the bends",
		"mission": "One program, three rooms with corners. Finish on the flag in every room.",
		"twist": "Every room turns a different number of times.",
		"rooms": ["One bend.", "Two bends.", "A winding path."],
		"blocks": ["res://puzzle/blocks/control flow/if.tres", "res://puzzle/blocks/control flow/else.tres", "res://level/objects/entities/robot/blocks/turn.tres"],
		"block_notes": ["Runs the blocks inside it only when its condition is True.", "Goes right under an if. Runs only when the if didn't.", "Turns the robot left, right, or back."],
	},
	"it_4": {
		"title": "Count the desks",
		"mission": "Stop the robot exactly on the flag.",
		"twist": "But there's only one move forward block, and it's already on the canvas.",
		"tip": "The Variables tab shows your variables while the program runs.",
		"blocks": ["res://puzzle/blocks/generic/initialize.tres", "res://puzzle/blocks/generic/increment.tres", "res://puzzle/blocks/socket/comparison.tres"],
		"block_notes": ["Makes a variable: a named box that holds a value.", "Adds 1 to a variable.", "Compares two values, like 2 < 5. Gives True or False."],
	},
	"it_5": {
		"title": "One block instead of three",
		"mission": "Get the robot around the corner and onto the flag.",
		"twist": "No while this time: for is the only way to repeat.",
		"blocks": ["res://puzzle/blocks/control flow/for_int.tres"],
		"block_notes": ["Counts from a start up to, not including, an end, and runs its blocks each time. From 1 until 5 runs 1, 2, 3, 4."],
	},
	"it_6": {
		"title": "A pattern, not a step",
		"mission": "Climb the staircase of desks and finish on the flag.",
		"twist": "But the for loop is already placed, and it's the only loop you get.",
		"tip": "Everything inside a loop repeats together, in order, on every pass.",
	},
	"it_7": {
		"title": "Aisle by aisle",
		"mission": "Drive down every aisle over every blue flag, then finish on the red flag.",
		"twist": "But the outer loop is already placed, one pass per aisle. What goes inside it is up to you.",
		"tip": "A loop can hold another loop. Give each loop its own variable name.",
	},
	"it_8": {
		"title": "Every row is longer",
		"mission": "Pass over every blue flag, row by row, then finish on the red flag.",
		"twist": "But every row of blue flags is longer than the one before it.",
		"tip": "A for loop's start and end can be variables, not only numbers.",
	},
	"it_9": {
		"title": "Two ways out",
		"mission": "One program, three rooms. In each room, stop on the flag or right before a puddle, whichever comes first.",
		"twist": "But the not block is missing this time.",
		"rooms": ["Finish on the flag.", "Stop right before the puddle.", "Finish on the flag."],
		"blocks": ["res://puzzle/blocks/control flow/break.tres", "res://puzzle/blocks/socket/boolean.tres"],
		"block_notes": ["Ends the loop it's in, right away.", "Always True, or always False."],
	},
	"it_10": {
		"title": "Back to the question",
		"mission": "One program, three winding rooms. Finish on the flag in every room.",
		"twist": "But there's no else block this time.",
		"blocks": ["res://puzzle/blocks/control flow/continue.tres"],
		"block_notes": ["Skips the rest of this pass and checks the loop's condition again."],
	},
	# Arrays. Generated alongside the scenes; keep the two in step.
	"ar_1": {
		"title": "Meet a list",
		"mission": "Watch the robot use the list on the wall to find the flag.",
		"blocks": ["res://puzzle/blocks/lists/item_of.tres", "res://level/objects/entities/robot/blocks/move_n.tres"],
		"block_notes": ["Gives you the value at an index.", "Moves forward that many times."],
		"tip": "In Python, this list is written route = [2, 3].",
		"show_stars": false,
	},
	"ar_2": {
		"title": "Read the board",
		"mission": "Now you build it: the robot uses the list to find the flag. One program has to work in all three rooms.",
		"twist": "Each room's list is different.",
		"rooms": ["Get to the flag.", "Get to the flag.", "Get to the flag."],
		"tip": "In Python, item 0 of route is written route[0].",
	},
	"ar_3": {
		"title": "Count, then the last",
		"mission": "Before the turn, go as far as the list is long. After the turn, go as far as its last value.",
		"twist": "Every list has a different length.",
		"rooms": ["Three values.", "Two values.", "Four values."],
		"blocks": ["res://puzzle/blocks/lists/length_of.tres", "res://puzzle/blocks/socket/arithmetic.tres"],
		"block_notes": ["Counts the values in a list.", "Does math: + - * / // %"],
		"block_values": ["list:route", ""],
		"tip": "In Python, length of route is written len(route).",
	},
	"ar_4": {
		"title": "Every stop",
		"mission": "Each value is how far to drive before the next left turn. Pass over every blue flag on the way to the red flag.",
		"twist": "Every list has a different number of stops.",
		"rooms": ["A lap.", "A spiral.", "A U-turn."],
		"tip": "for stops before its end number, like Python's range: from 0 until 3 runs 0, 1, 2.",
	},
	"ar_5": {
		"title": "Every stop, again",
		"mission": "The same rooms as last time.",
		"twist": "But there's no item of or length of.",
		"rooms": ["A lap.", "A spiral.", "A U-turn."],
		"blocks": ["res://puzzle/blocks/control flow/for_each.tres"],
		"block_notes": ["Runs its blocks once for each value in a list. The box it is on lights up."],
		"block_values": ["leg,list:route"],
		"tip": "In Python: for leg in route:",
	},
	"ar_6": {
		"title": "There and back",
		"mission": "Drive out to the blue flag, then drive back the same way to the red flag where you started.",
		"twist": "The way back is the list, read backwards.",
		"rooms": ["A long way out.", "A winding way out.", "A short way out."],
		"tip": "for can count down: give it a step of -1.",
	},
	"ar_7": {
		"title": "Number the lockers",
		"mission": "Give every locker its number.",
		"twist": "People count lockers from 1, not 0.",
		"rooms": ["Three lockers.", "Five lockers.", "Four lockers."],
		"blocks": ["res://puzzle/blocks/lists/set_item.tres"],
		"block_notes": ["Changes the value at an index."],
		"block_values": ["0,list:lockers,1"],
		"tip": "In Python: lockers[0] = 1",
	},
	"ar_8": {
		"title": "Passing marks",
		"mission": "Copy every score of 75 or more into passed, in the same order.",
		"twist": "passed starts empty.",
		"rooms": ["Five scores.", "Four scores.", "Six scores."],
		"blocks": ["res://puzzle/blocks/lists/append.tres"],
		"block_notes": ["Adds a value to the end of a list."],
		"block_values": ["82,list:passed"],
		"tip": "In Python: passed.append(s)",
	},
	"ar_9": {
		"title": "Tidy up",
		"mission": "Copy bags into tidy, but skip a value that is the same as the one just before it. The flag is as far away as tidy is long.",
		"twist": "A value can come back later. Then it stays.",
		"rooms": ["Six bags.", "Five bags.", "Four bags."],
		"tip": "!= means \"is not equal to\".",
	},
	"ar_10": {
		"title": "In both",
		"mission": "Put every student who is in both chess and choir into both.",
		"twist": "Some rooms have nobody in both.",
		"rooms": ["Four in chess.", "Two in chess.", "Three in chess."],
		"blocks": ["res://puzzle/blocks/lists/contains.tres"],
		"block_notes": ["True if the value is somewhere in the list."],
		"block_values": ["2,list:choir"],
		"tip": "In Python: s in choir",
	},
	"ar_11": {
		"title": "Here either day",
		"mission": "Put everyone who came on mon or tue into present, once each.",
		"twist": "Some students came on both days.",
		"rooms": ["Three and three.", "Two and two.", "Four and two."],
		"tip": "not flips True and False.",
	},
}


static func for_scene(scene_path: String) -> Dictionary:
	return BRIEFS.get(scene_path.get_file().get_basename(), {})
